# Generated by Django 3.0 on 2020-01-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.CharField(choices=[('Advertiser', 'Advertiser'), ('Shopkeeper', 'Shopkeeper')], max_length=20, null=True),
        ),
    ]
