# Generated by Django 3.0 on 2020-02-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0007_auto_20200118_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile_info',
        ),
    ]
