# Generated by Django 3.0 on 2020-02-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0008_delete_profile_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
