# Generated by Django 3.0 on 2020-02-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0010_auto_20200207_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
