# Generated by Django 3.0 on 2020-02-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0011_advertiser_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
