# Generated by Django 3.0 on 2020-02-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0015_auto_20200208_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertiser',
            old_name='user',
            new_name='user_ID',
        ),
    ]
