# Generated by Django 3.0 on 2020-02-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0017_auto_20200208_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='user',
        ),
    ]
