# Generated by Django 3.0 on 2020-02-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0021_auto_20200208_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertiser',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
