# Generated by Django 3.0 on 2020-02-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0022_auto_20200208_1742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='advertiser',
        ),
    ]
