# Generated by Django 3.0 on 2020-02-09 06:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testpro', '0024_addetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdDetail',
            new_name='AdDetails',
        ),
    ]
