# Generated by Django 3.0 on 2020-02-09 06:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testpro', '0025_auto_20200209_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdDetails',
            new_name='AdDetail',
        ),
    ]
