# Generated by Django 3.0 on 2020-03-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0032_auto_20200309_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
