# Generated by Django 3.0 on 2020-03-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0034_customer_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
