# Generated by Django 3.0 on 2020-03-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0037_auto_20200315_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='users',
        ),
    ]
