# Generated by Django 3.0 on 2020-03-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0040_auto_20200319_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=200, null=True),
        ),
    ]
