# Generated by Django 3.0 on 2020-03-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0042_auto_20200319_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.ManyToManyField(to='testpro.Places'),
        ),
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.ManyToManyField(to='testpro.Area'),
        ),
    ]
