# Generated by Django 3.0 on 2020-03-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0043_auto_20200319_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
