# Generated by Django 3.0 on 2020-03-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0044_auto_20200319_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='date_create',
            field=models.DateField(auto_now=True),
        ),
    ]
