# Generated by Django 3.0 on 2020-03-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0045_places_date_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='date_create',
        ),
    ]
