# Generated by Django 3.0 on 2020-03-19 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0047_auto_20200319_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adname', models.CharField(max_length=500)),
                ('ads', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='adver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testpro.Advertise'),
        ),
    ]
