# Generated by Django 3.0 on 2020-03-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0048_auto_20200320_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='addetail',
            name='place',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertise',
            name='ads',
            field=models.FileField(upload_to='ads'),
        ),
    ]
