# Generated by Django 3.0 on 2020-05-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0050_auto_20200502_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
    ]
