# Generated by Django 3.0 on 2020-05-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testpro', '0054_auto_20200505_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testpro.Customer'),
        ),
    ]
